/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenialsIndexRouteImport } from './routes/denials/index'
import { Route as ClaimsIndexRouteImport } from './routes/claims/index'
import { Route as DenialsDenialIdRouteImport } from './routes/denials/$denialId'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims/$claimId'
import { Route as AdminSeedRouteImport } from './routes/admin/seed'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenialsIndexRoute = DenialsIndexRouteImport.update({
  id: '/denials/',
  path: '/denials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenialsDenialIdRoute = DenialsDenialIdRouteImport.update({
  id: '/denials/$denialId',
  path: '/denials/$denialId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/admin/seed',
  path: '/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/admin/seed': typeof AdminSeedRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/denials/$denialId': typeof DenialsDenialIdRoute
  '/claims/': typeof ClaimsIndexRoute
  '/denials/': typeof DenialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/admin/seed': typeof AdminSeedRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/denials/$denialId': typeof DenialsDenialIdRoute
  '/claims': typeof ClaimsIndexRoute
  '/denials': typeof DenialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/admin/seed': typeof AdminSeedRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/denials/$denialId': typeof DenialsDenialIdRoute
  '/claims/': typeof ClaimsIndexRoute
  '/denials/': typeof DenialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/admin/seed'
    | '/claims/$claimId'
    | '/denials/$denialId'
    | '/claims/'
    | '/denials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/admin/seed'
    | '/claims/$claimId'
    | '/denials/$denialId'
    | '/claims'
    | '/denials'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/admin/seed'
    | '/claims/$claimId'
    | '/denials/$denialId'
    | '/claims/'
    | '/denials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  AdminSeedRoute: typeof AdminSeedRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  DenialsDenialIdRoute: typeof DenialsDenialIdRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
  DenialsIndexRoute: typeof DenialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denials/': {
      id: '/denials/'
      path: '/denials'
      fullPath: '/denials/'
      preLoaderRoute: typeof DenialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denials/$denialId': {
      id: '/denials/$denialId'
      path: '/denials/$denialId'
      fullPath: '/denials/$denialId'
      preLoaderRoute: typeof DenialsDenialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/admin/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  AdminSeedRoute: AdminSeedRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  DenialsDenialIdRoute: DenialsDenialIdRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
  DenialsIndexRoute: DenialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
